import { useAuth } from "@/_core/hooks/useAuth";
import { LanguageToggle, usePublicLanguage } from "@/components/LanguageToggle";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Check, ChevronRight, Mail, ShieldCheck, Unplug } from "lucide-react";
import { useLocation } from "wouter";

export default function StudentSettings() {
  const [, setLocation] = useLocation();
  const { user } = useAuth();
  const { language, isArabic, toggleLanguage } = usePublicLanguage();
  const relationship = trpc.student.universityRelationshipWorkspace.useQuery(undefined, { enabled: !!user });
  const utils = trpc.useUtils();
  const disconnectGmail = trpc.student.disconnectStudentGmail.useMutation({ onSuccess: () => void utils.student.universityRelationshipWorkspace.invalidate() });
  const isConnected = Boolean(relationship.data?.inboxConnection);
  const copy = isArabic ? {
    eyebrow: "إعداداتك", title: "بريدك. قرارك. سجلّك.", body: "اربط Gmail الخاص فيك حتى تراجع وترسل رسائل الجامعات من بريدك الحقيقي. نايتفول ما بتبعت أي رسالة تلقائياً.", back: "الرجوع للرحلة", section: "البريد الموصول", gmail: "Gmail وGoogle Workspace", connected: "موصول", notConnected: "غير موصول", connect: "اربط Gmail", disconnect: "افصل Gmail", setup: "الربط راح يفتح تسجيل دخول Google عادي. ما في مفاتيح API أو إعدادات تقنية على الطالب.", rules: ["كل رسالة بدها موافقة منك قبل الإرسال.", "نايتفول ما بتبعت تلقائياً ولا بتعمل حملات.", "بتقدر تفصل بريدك بأي وقت."]
  } : {
    eyebrow: "YOUR SETTINGS", title: "Your inbox. Your decision. Your record.", body: "Connect your personal Gmail or Google Workspace inbox to review and send university messages from the address admissions teams already know. Nightfall never sends automatically.", back: "Back to my journey", section: "CONNECTED INBOX", gmail: "Gmail & Google Workspace", connected: "Connected", notConnected: "Not connected", connect: "Connect Gmail", disconnect: "Disconnect Gmail", setup: "Connecting opens the normal Google sign-in and consent screen. Students never enter API keys or technical settings.", rules: ["Every individual email needs your approval before it can send.", "Nightfall never runs outreach campaigns or auto-sends follow-ups.", "You can disconnect your inbox at any time."]
  };
  return <div dir={isArabic ? "rtl" : "ltr"} className="night-bloom min-h-screen text-white"><header className="border-b border-white/10 bg-[#0b0d0e]/92 px-5 py-4 backdrop-blur-xl sm:px-8"><div className="mx-auto flex max-w-[1180px] items-center justify-between"><button type="button" onClick={() => setLocation("/dashboard?tab=reach")} className="nf-button flex items-center gap-2 text-xs text-[#cbd4ce]"><ArrowLeft className={`h-4 w-4 ${isArabic ? "rotate-180" : ""}`} />{copy.back}</button><LanguageToggle language={language} onToggle={toggleLanguage} /></div></header><main className="mx-auto max-w-[1180px] px-5 py-12 sm:px-8"><p className="nf-label text-[#a9b3ac]">// {copy.eyebrow}</p><h1 className="mt-3 max-w-3xl text-4xl font-semibold leading-[.9] tracking-[-.07em] sm:text-6xl">{copy.title}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-[#9da8a1]">{copy.body}</p><section className="mt-10 grid gap-5 lg:grid-cols-[minmax(0,1fr)_340px]"><div className="border border-white/15 bg-[#111516] p-6"><div className="flex items-start justify-between gap-5"><div><p className="nf-label text-[8px] text-[#a9b3ac]">// {copy.section}</p><h2 className="mt-4 flex items-center gap-3 text-2xl font-semibold"><Mail className="h-5 w-5" />{copy.gmail}</h2><p className="mt-3 text-sm text-[#a9b3ad]">{isConnected ? relationship.data?.inboxConnection?.emailAddress : copy.setup}</p></div><span className={`border px-2.5 py-1 nf-label text-[8px] ${isConnected ? "border-white bg-white text-black" : "border-white/20 text-[#cbd4ce]"}`}>{isConnected ? copy.connected : copy.notConnected}</span></div><div className="mt-7 border-t border-white/10 pt-5">{isConnected ? <button type="button" disabled={disconnectGmail.isPending} onClick={() => disconnectGmail.mutate()} className="nf-button flex items-center gap-2 border border-white/20 px-4 py-3 text-xs hover:bg-white hover:text-black disabled:opacity-50"><Unplug className="h-4 w-4" />{disconnectGmail.isPending ? "…" : copy.disconnect}</button> : <button type="button" onClick={() => window.location.assign("/api/gmail/connect")} className="nf-button flex items-center gap-2 border border-white px-4 py-3 text-xs font-semibold hover:bg-white hover:text-black"><Mail className="h-4 w-4" />{copy.connect}<ChevronRight className={`h-4 w-4 ${isArabic ? "rotate-180" : ""}`} /></button>}</div></div><aside className="border border-white/15 bg-[#111516] p-6"><ShieldCheck className="h-5 w-5" /><div className="mt-5 space-y-4">{copy.rules.map((rule) => <div key={rule} className="flex gap-3"><Check className="mt-0.5 h-4 w-4 shrink-0" /><p className="text-sm leading-6 text-[#c3cdc6]">{rule}</p></div>)}</div></aside></section></main></div>;
}
