import { AIChatBox, type Message } from "@/components/AIChatBox";
import { Compass, ShieldCheck, Sparkles } from "lucide-react";

export function ConsultingChat({ language, messages, isLoading, onSend }: { language: "en" | "ar"; messages: Message[]; isLoading: boolean; onSend: (content: string) => void }) {
  const ar = language === "ar";
  const t = ar ? {
    kicker: "نايتفول كونسلتينغ", title: "خلّينا نرتّب الصورة سوا.", body: "اسأل عن اختياراتك، المواعيد، الأوراق، أو تواصلك مع الجامعات. الاستشارة بتعتمد على رحلة نايتفول الخاصة فيك—بس القرار دايماً إلك.", context: "بتشوف سياقك الخاص", points: ["الجامعات والبرامج المحفوظة", "المواعيد، الخطوات، والأوراق", "المسودات والمتابعات الجامعية"], boundary: "المساعدة ما بتقرر أهليتك أو فرص قبولك، وما بتغيّر أو بتبعت أي شي عنك.", empty: "بلّش بسؤال صغير أو اختار نقطة من وضعك الحالي.", placeholder: "مثلاً: شو أهم خطوة إلي هالأسبوع؟", prompts: ["شو أهم خطوة إلي هالأسبوع؟", "شو لازم أتأكد منه قبل ما أراسل الجامعة؟", "رتّبلي أولوياتي بين البرامج المحفوظة"],
  } : {
    kicker: "NIGHTFALL CONSULTING", title: "Let’s make the picture clearer.", body: "Ask about your choices, dates, documents, or university relationships. Guidance uses your private Nightfall journey—but every decision remains yours.", context: "PRIVATE CONTEXT IN VIEW", points: ["Saved universities and programmes", "Deadlines, milestones, and documents", "University drafts and follow-ups"], boundary: "Consulting does not determine eligibility or admission chances, and it never sends or changes anything for you.", empty: "Start with one small question or choose a prompt grounded in your current journey.", placeholder: "For example: What should I focus on this week?", prompts: ["What should I focus on this week?", "What should I verify before emailing a university?", "Help me prioritize my saved programmes"],
  };
  return <section className="pb-12"><div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_330px]"><div><p className="nf-label text-[#a9b3ac]">// {t.kicker}</p><h1 className="mt-3 max-w-3xl text-4xl font-semibold leading-[.9] tracking-[-.07em] sm:text-6xl">{t.title}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-[#9da8a1]">{t.body}</p></div><aside className="border border-white/15 bg-[#111516] p-5"><div className="flex items-center gap-3"><Compass className="h-5 w-5" /><p className="nf-label text-[8px] text-[#a9b3ac]">{t.context}</p></div><div className="mt-5 space-y-3">{t.points.map((point) => <p key={point} className="flex gap-3 text-sm leading-6 text-[#d6dfd9]"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-white" />{point}</p>)}</div></aside></div><div className="mt-8 grid gap-5 lg:grid-cols-[minmax(0,1fr)_300px]"><div className="overflow-hidden border border-white/15 bg-[#111516]"><AIChatBox messages={messages} onSendMessage={onSend} isLoading={isLoading} placeholder={t.placeholder} emptyStateMessage={t.empty} suggestedPrompts={t.prompts} height="620px" className="rounded-none border-0 bg-transparent text-white shadow-none" /></div><aside className="border border-white/15 bg-[#111516] p-5"><Sparkles className="h-5 w-5" /><p className="mt-5 nf-label text-[8px] text-[#a9b3ac]">// REVIEW-FIRST GUIDANCE</p><p className="mt-3 text-sm leading-6 text-[#c7d0ca]">{t.boundary}</p><div className="mt-6 border-t border-white/10 pt-5"><ShieldCheck className="h-4 w-4" /><p className="mt-3 text-xs leading-5 text-[#99a49e]">{ar ? "لما تحتاج تفاصيل حديثة أو رسمية، رح نقولك شو تتحقق منه ومن أي مصدر." : "When a detail is time-sensitive or official, Nightfall will point to what you should verify and where."}</p></div></aside></div></section>;
}
