import { trpc } from "@/lib/trpc";
import { betaAccess } from "@/lib/betaAccess";
import { discoveryCatalog } from "@/lib/universityDiscovery";
import { BellRing, Check, ExternalLink, Eye, Loader2, Radio, ShieldCheck } from "lucide-react";

type SavedUniversity = { id: number; university: string; program: string; sourceUrl: string | null; snapshotSummary: string | null; imageUrl: string | null; imageAttribution: string | null };

export function UniversityWatchPanel({ universities, language, isArabic }: { universities: SavedUniversity[]; language: "en" | "ar"; isArabic: boolean }) {
  const utils = trpc.useUtils();
  const watches = trpc.student.universityRequirementWatches.useQuery();
  const sourceCaches = trpc.student.universityWatchSourceCaches.useQuery();
  const preferences = trpc.student.universityWatchPreferences.useQuery();
  const alerts = trpc.student.universityRequirementAlerts.useQuery();
  const updateWatch = trpc.student.updateUniversityRequirementWatch.useMutation({ onSuccess: () => { void utils.student.universityRequirementWatches.invalidate(); void utils.student.universityWatchSourceCaches.invalidate(); } });
  const updatePreferences = trpc.student.updateUniversityWatchPreferences.useMutation({ onSuccess: () => void utils.student.universityWatchPreferences.invalidate() });
  const markRead = trpc.student.markUniversityRequirementAlertRead.useMutation({ onSuccess: () => void utils.student.universityRequirementAlerts.invalidate() });
  const english = language === "en";
  const watched = new Set((watches.data ?? []).filter((watch) => watch.enabled).map((watch) => watch.universityId));
  const cacheByUrl = new Map((sourceCaches.data ?? []).map((cache) => [cache.sourceUrl, cache]));

  const sourceFor = (university: SavedUniversity) => {
    const catalog = discoveryCatalog.find((entry) => entry.university === university.university);
    return {
      sourceUrl: university.sourceUrl || catalog?.sourceUrl,
      sourceLabel: `${university.university} · ${university.program}`,
      imageUrl: university.imageUrl || catalog?.imageUrl,
      imageAttribution: university.imageAttribution || catalog?.imageAttribution,
      summary: cacheByUrl.get(university.sourceUrl || catalog?.sourceUrl || "")?.summary || university.snapshotSummary || catalog?.snapshotSummary,
    };
  };

  return <section className="space-y-5">
    <div className="relative overflow-hidden border border-white/15 bg-[#111516] p-6 sm:p-8">
      <div className="night-orbit absolute -right-16 -top-16 h-56 w-56 border-white/10" />
      <div className="relative max-w-3xl"><p className="nf-label text-[#a9b3ac]">// {english ? "BETA / OFFICIAL-PAGE WATCH" : "بيتا / متابعة الصفحات الرسمية"}</p><h1 className="mt-3 text-4xl font-semibold leading-[.92] tracking-[-.07em] sm:text-6xl">{english ? "Your research should keep paying off." : "بحثك لازم يضل يفيدك."}</h1><p className="mt-5 max-w-2xl text-sm leading-7 text-[#aeb8b1]">{english ? "Nightfall caches the official programme page you choose. It compares the page first and only uses a concise AI explanation when the source genuinely changes. Nothing is submitted, and every alert points back to the university." : "نايتفول بتخزّن صفحة البرنامج الرسمية اللي بتختارها. بتقارن الصفحة بالأول وبتستخدم تفسير ذكي مختصر بس لما المصدر يتغيّر فعلاً. ما في أي تقديم تلقائي، وكل تنبيه بيرجعك للجامعة."}</p></div>
      <div className="relative mt-7 flex flex-wrap gap-2"><span className="border border-white/20 px-3 py-2 nf-label text-[9px] text-[#d8e0db]">{english ? "BETA ACCESS OPEN" : "الوصول التجريبي مفتوح"}</span><span className="border border-white/10 px-3 py-2 nf-label text-[9px] text-[#aeb8b1]">{english ? "OFFICIAL SOURCES ONLY" : "مصادر رسمية فقط"}</span><span className="border border-white/10 px-3 py-2 nf-label text-[9px] text-[#aeb8b1]">{english ? "AI ON REAL CHANGE" : "الذكاء عند تغيير فعلي"}</span></div>
      <div className="relative mt-5 grid gap-3 border-t border-white/10 pt-5 text-xs leading-5 text-[#98a39c] sm:grid-cols-2"><p>{english ? betaAccess.current[1] : "متابعة الصفحات الرسمية مفتوحة للبرامج اللي الطالب بيختار يراقبها."}</p><p>{english ? betaAccess.later[0] : "البحث الذكي الأوسع لقوائم كبيرة رح يضل أتمتة اختيارية، مش بحث متكرر بصمت."}</p></div>
    </div>

    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_330px]">
      <div className="border border-white/15 bg-[#111516] p-5"><div className="flex items-start justify-between gap-4"><div><p className="nf-label text-[#9ba59f]">// {english ? "SAVED SOURCES" : "مصادرك المحفوظة"}</p><h2 className="mt-2 text-xl font-semibold">{english ? "Choose what deserves a quiet watch." : "اختار شو بستاهل متابعة هادئة."}</h2></div><Eye className="h-5 w-5 shrink-0" /></div><div className="mt-6 space-y-3">{universities.map((university) => { const source = sourceFor(university); const enabled = watched.has(university.id); return <article key={university.id} className="overflow-hidden border border-white/10 bg-black/10 sm:grid sm:grid-cols-[132px_1fr]"><div className="relative min-h-[118px] overflow-hidden bg-white/5">{source.imageUrl ? <img src={source.imageUrl} alt="" className="absolute inset-0 h-full w-full object-cover opacity-70 grayscale" /> : <div className="absolute inset-0 night-orbit m-auto h-20 w-20 border-white/15" />}</div><div className="p-4"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold">{university.university}</p><p className="mt-1 text-xs text-[#aeb8b1]">{university.program}</p></div><button onClick={() => source.sourceUrl && updateWatch.mutate({ universityId: university.id, enabled: !enabled, sourceUrl: source.sourceUrl, sourceLabel: source.sourceLabel })} disabled={!source.sourceUrl || updateWatch.isPending} className={`nf-button shrink-0 border px-3 py-2 text-[10px] font-bold uppercase tracking-[.08em] ${enabled ? "border-white bg-white text-black" : "border-white/20 text-[#d7dfda]"}`}>{enabled ? <span className="flex items-center gap-1"><Check className="h-3 w-3" />{english ? "Watching" : "متابعة"}</span> : english ? "Watch" : "راقب"}</button></div>{source.summary && <p className="mt-3 text-xs leading-5 text-[#aeb8b1]">{source.summary}</p>}<div className="mt-4 flex items-center justify-between gap-3"><span className="nf-mono text-[8px] text-[#88928b]">{source.imageAttribution || (english ? "Official programme source" : "مصدر البرنامج الرسمي")}</span>{source.sourceUrl && <a href={source.sourceUrl} target="_blank" rel="noreferrer" className="nf-button flex items-center gap-1 text-[10px] font-semibold text-white underline underline-offset-4">{english ? "Open source" : "افتح المصدر"}<ExternalLink className="h-3 w-3" /></a>}</div></div></article>; })}{!universities.length && <p className="border border-dashed border-white/20 p-7 text-sm leading-6 text-[#9da79f]">{english ? "Save a university from Discover first. Then you can choose exactly which official pages Nightfall should watch." : "احفظ جامعة من الاكتشاف بالأول. بعدها بتقدر تختار أي صفحات رسمية نايتفول تتابعها."}</p>}</div></div>
      <aside className="border border-white/15 bg-[#111516] p-5"><Radio className="h-5 w-5" /><p className="mt-6 nf-label text-[#9ba59f]">// {english ? "WEEKLY RHYTHM" : "إيقاع أسبوعي"}</p><h2 className="mt-2 text-xl font-semibold">{english ? "Small, deliberate checks." : "فحوصات صغيرة ومقصودة."}</h2><p className="mt-3 text-sm leading-6 text-[#9ca69f]">{english ? "One weekly check keeps beta costs low. The source is cached, unchanged pages stay quiet, and a source change becomes a review card." : "فحص أسبوعي واحد بخفف كلفة البيتا. المصدر بيتخزّن، الصفحات الثابتة بتضل هادية، والتغيير الحقيقي بصير بطاقة للمراجعة."}</p><label className="mt-5 flex items-center justify-between border border-white/10 px-3 py-3"><span className="text-xs text-[#d9e1dc]">{english ? "Weekly UTC hour" : "ساعة UTC أسبوعية"}</span><select value={preferences.data?.preferredHourUtc ?? 10} onChange={(event) => updatePreferences.mutate({ enabled: preferences.data?.enabled ?? false, preferredHourUtc: Number(event.target.value) })} className="bg-transparent nf-mono text-xs outline-none">{Array.from({ length: 24 }, (_, hour) => <option key={hour} value={hour}>{String(hour).padStart(2, "0")}:00</option>)}</select></label><button onClick={() => updatePreferences.mutate({ enabled: !(preferences.data?.enabled ?? false), preferredHourUtc: preferences.data?.preferredHourUtc ?? 10 })} disabled={updatePreferences.isPending} className={`nf-button mt-3 flex w-full items-center justify-center gap-2 border px-4 py-3 text-xs font-bold ${preferences.data?.enabled ? "border-white bg-white text-black" : "border-white/20 text-white"}`}>{updatePreferences.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <BellRing className="h-4 w-4" />}{preferences.data?.enabled ? (english ? "Weekly watch on" : "المتابعة الأسبوعية مفعّلة") : (english ? "Start weekly watch" : "ابدأ المتابعة الأسبوعية")}</button><p className="mt-3 nf-mono text-[9px] leading-5 text-[#87918a]">{english ? "Monday at your chosen UTC hour. You can pause it anytime." : "كل إثنين بساعة UTC اللي اخترتها. فيك توقّفها بأي وقت."}</p>{updatePreferences.error && <p className="mt-3 text-xs text-[#e4eae6]">{updatePreferences.error.message}</p>}</aside>
    </div>

    <section className="grid gap-px border border-white/15 bg-white/10 md:grid-cols-2"><div className="bg-[#101415] p-5"><p className="nf-label text-[#a2aca5]">// {english ? "OPEN IN THIS BETA" : "مفتوح بهالبيتا"}</p><div className="mt-4 space-y-3">{betaAccess.current.map((item) => <p key={item} className="flex gap-2 text-xs leading-6 text-[#dce3de]"><span className="nf-mono text-[#9aa49d]">●</span>{english ? item : ["اكتشاف الجامعات، المقارنة، روابط المصادر، وصفحات البرامج المحفوظة مفتوحة بالبيتا.", "متابعة الصفحات الرسمية مفتوحة للبرامج اللي الطالب بيختار يراقبها.", "مراجعة كشف العلامات وتخطيط المواعيد بإيد الطالب وبأسلوب مراجعة أولاً."][betaAccess.current.indexOf(item)]}</p>)}</div></div><div className="bg-[#111516] p-5"><p className="nf-label text-[#a2aca5]">// {english ? "LATER, WITH YOUR APPROVAL" : "لاحقاً، بموافقتك"}</p><div className="mt-4 space-y-3">{betaAccess.later.map((item) => <p key={item} className="flex gap-2 text-xs leading-6 text-[#aeb8b1]"><span className="nf-mono text-[#9aa49d]">→</span>{english ? item : ["البحث الذكي الأوسع لقوائم كبيرة رح يكون خيار إضافي، مش بحث متكرر بصمت.", "أي أتمتة مستقبلية للبوابات أو الإيميل بدها موافقة منفصلة وقت التنفيذ.", "نايتفول ما بتفرض دفع، ما بتقفل مزايا، وما بتاخد قرارات قبول بهالفترة التجريبية."][betaAccess.later.indexOf(item)]}</p>)}</div></div></section>

    <section className="border border-white/15 bg-[#111516] p-5"><div className="flex items-start justify-between gap-4"><div><p className="nf-label text-[#9ba59f]">// {english ? "SOURCE CHANGES TO REVIEW" : "تغييرات بالمصدر للمراجعة"}</p><h2 className="mt-2 text-xl font-semibold">{english ? "A change is a prompt to look closer." : "التغيير دعوة إنك تدقّق أكتر."}</h2></div><ShieldCheck className="h-5 w-5" /></div><div className="mt-5 space-y-3">{(alerts.data ?? []).map((alert) => <article key={alert.id} className={`border p-4 ${alert.read ? "border-white/10" : "border-white/30 bg-white/5"}`}><p className="text-sm font-semibold">{alert.title}</p><p className="mt-2 max-w-3xl text-xs leading-6 text-[#aeb8b1]">{alert.body}</p><div className="mt-4 flex flex-wrap items-center gap-4"><a href={alert.sourceUrl} target="_blank" rel="noreferrer" className="nf-button flex items-center gap-1 text-[10px] font-semibold underline underline-offset-4">{english ? "Review official page" : "راجع الصفحة الرسمية"}<ExternalLink className="h-3 w-3" /></a>{!alert.read && <button onClick={() => markRead.mutate({ id: alert.id })} className="nf-button text-[10px] font-semibold underline underline-offset-4">{english ? "Mark reviewed" : "علّم كمراجع"}</button>}</div></article>)}{!(alerts.data ?? []).length && <p className="border border-dashed border-white/15 p-6 text-sm leading-6 text-[#909b94]">{english ? "No source changes to review yet. Nightfall will stay quiet until one of the official pages you selected genuinely changes." : "ما في تغييرات بالمصادر للمراجعة لسه. نايتفول رح تضل هادية لحد ما صفحة رسمية اخترتها تتغيّر فعلاً."}</p>}</div></section>
  </section>;
}
