import { Inbox, Loader2, RefreshCw, ShieldCheck } from "lucide-react";

type Reply = { id: number; direction: "outbound" | "inbound"; university: string; subject: string; body: string; category: string; aiNextStep: string | null; aiReviewNote: string | null; receivedAt: Date | null };

export function UniversityReplyReviewPanel({ language, inboxConnected, replies, isSyncing, onSync }: { language: "en" | "ar"; inboxConnected: boolean; replies: Reply[]; isSyncing: boolean; onSync: () => void }) {
  const ar = language === "ar";
  const t = ar ? { kicker: "ردود Gmail", title: "راجع الرد قبل ما تعمل أي خطوة.", body: "المزامنة بتقرأ آخر ردود من جهات الاتصال الجامعية اللي أكّدتها فقط. ما في رد تلقائي.", sync: "زامن الردود", unavailable: "اربط Gmail من الإعدادات حتى تقدر تراجع الردود.", empty: "ما في ردود جامعية جديدة للمراجعة.", next: "الخطوة المقترحة", review: "حدّ المراجعة" } : { kicker: "GMAIL REPLIES", title: "Review the reply before taking any action.", body: "Sync checks recent messages only from university contacts you confirmed. It never replies automatically.", sync: "Sync replies", unavailable: "Connect Gmail in Settings to review university replies.", empty: "No university replies are waiting for review.", next: "SUGGESTED NEXT STEP", review: "REVIEW BOUNDARY" };
  return <section className="mt-5 border border-white/15 bg-[#111516] p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="nf-label text-[8px] text-[#a9b3ac]">// {t.kicker}</p><h2 className="mt-3 text-2xl font-semibold tracking-[-.04em]">{t.title}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#a5afa9]">{t.body}</p></div><button type="button" disabled={isSyncing || !inboxConnected} onClick={onSync} className="nf-button flex shrink-0 items-center justify-center gap-2 border border-white/30 px-4 py-3 text-[10px] font-semibold hover:bg-white hover:text-black disabled:opacity-40"><RefreshCw className={`h-3.5 w-3.5 ${isSyncing ? "animate-spin" : ""}`} />{isSyncing ? "…" : t.sync}</button></div>{!inboxConnected && <p className="mt-5 border-t border-white/10 pt-4 text-xs text-[#9fa9a3]">{t.unavailable}</p>}<div className="mt-5 grid gap-3 md:grid-cols-2">{replies.map((reply) => <article key={reply.id} className="border border-white/10 bg-black/15 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">{reply.subject}</p><p className="mt-1 text-[11px] text-[#a7b1ab]">{reply.university}</p></div><Inbox className="h-4 w-4 shrink-0" /></div><p className="mt-3 line-clamp-3 text-xs leading-5 text-[#c5cec8]">{reply.body}</p><div className="mt-4 border-t border-white/10 pt-3"><p className="nf-label text-[8px] text-[#9ba59f]">{t.next}</p><p className="mt-1 text-xs leading-5 text-[#e0e7e2]">{reply.aiNextStep || reply.category}</p><div className="mt-3 flex gap-2 border-l-2 border-white pl-3"><ShieldCheck className="mt-0.5 h-3.5 w-3.5 shrink-0" /><div><p className="nf-label text-[8px] text-[#9ba59f]">{t.review}</p><p className="mt-1 text-[11px] leading-5 text-[#aeb8b1]">{reply.aiReviewNote || "Read the original university email before acting."}</p></div></div></div></article>)}{!replies.length && <p className="border border-dashed border-white/15 p-5 text-sm text-[#9ca69f]">{t.empty}</p>}</div></section>;
}
